[AR-1885] Include Exception#cause in error reports
indigobio/logatron pull request #21
Opened 2017-08-09 20:14 UTC by crgee

2017-08-09 20:22 UTC, jwliechty requested changes

2017-08-09 20:22 UTC, jwliechty commented on lib/logatron/error_formatter.rb
> +          .map { |e| "  caused by: #{format_message(e)}\n#{format_backtrace(e)}" }
What about metadata in causes?

2017-08-09 20:22 UTC, jwliechty commented on spec/lib/logatron/error_formatter_spec.rb
> +    at g
I would like to see a real log with this.

2017-08-09 20:22 UTC, jwliechty commented on lib/logatron/logatron.rb
> +    def log_exception(e, severity, additional_info = {}, error_formatter = Logatron::ErrorFormatter.new)
The `ErrorFormatter` seems like it should be a configuration setting for Logatron in general. Is there usefulness in allowing the error formatting to set when invoking the method as opposed to configuring Logatron at startup?

2017-08-09 20:22 UTC, jwliechty commented on .ruby-version
> +2.4.1
Weren't we getting rid of these ruby version files in gems? I think Jacob is the one to ask.

2017-08-09 22:58 UTC, wintonpc commented on lib/logatron/error_formatter.rb
> +          .map { |e| "  caused by: #{format_message(e)}\n#{format_backtrace(e)}" }
It now uses `Exception#meta`, if present

2017-08-09 23:10 UTC, wintonpc commented on lib/logatron/logatron.rb
> +    def log_exception(e, severity, additional_info = {}, error_formatter = Logatron::ErrorFormatter.new)
good idea. done.

2017-08-11 15:19 UTC, jwliechty approved these changes
Nice work!

2017-08-11 15:22 UTC, merged